In [1]:
import inferProgram
inferProgram.Acc(101).infer_image('test_image/cs/7.jpg')

< 0.99999905
n 0.91414833
1 0.996238
0 0.99999416
- 0.9999987
- 0.9999976
0 0.9999987
1 0.9993494
- 0.99954444
n 0.9918229
2 0.9999511
+ 0.9999993
n 0.9477107
1 0.97108895
2 0.9999918
+ 0.99999857
n 0.5574481
2 0.99970156
+ 0.9999783
2 0.9999914
0 0.9999926
< n
n 0.7788461538461539
< 1
< 0
1 0
< 0
0 0
< 1
- 1
n 2
+ 1
1 2
2 n
+ 2
+ 2
- 0
2 0
['<', [['1', [], [], [], [337, 59, 20, 78]], ['0', [], [], [], [359, 78, 37, 44]], ['0', [], [], [], [405, 76, 30, 47]]], [], [['n', [], [], [], [324, 266, 45, 65]], ['-', [], [], [['-', [], [], [], [389, 299, 38, 13]]], [387, 280, 34, 9]], ['1', [], [], [], [450, 267, 12, 69]]], [108, 104, 196, 208]]
['-', [['n', [['2', [], [], [], [661, 55, 35, 34]]], [], [], [602, 90, 52, 66]], ['+', [], [], [], [709, 83, 63, 63]], ['1', [], [], [], [787, 75, 15, 65]], ['2', [], [], [], [808, 74, 53, 68]], ['n', [], [], [], [875, 77, 47, 68]], ['+', [], [], [], [964, 53, 68, 80]], ['2', [], [], [], [1045, 50, 56, 68]], ['0', [], [], [], [1109, 64, 48, 54]]], [], 

(True, '<^(100)~(n=1)((n^(2)+12n+20)/(n+2))')

In [1]:
import inferProgram
aaa = inferProgram.Unk(66)

In [2]:
re = aaa.infer_image('test_image/cs/5.jpg')[1][0]
print(re)
inferProgram.ToolBar.getDerivative().getResult(re)

y 0.99995196
- 0.9999881
- 0.9999931
* 0.99997914
3 0.9999938
( 0.8912689
n 0.9999982
* 0.9986847
+ 0.9999361
e 0.99999905
* 0.9737428
* 0.9995753
2 0.9996662
+ 0.9999739
* 0.9946801
+ 0.99927014
1 0.996992
['y', [], [], [], [113, 50, 56, 113]]
['-', [['-', [], [], [], [218, 74, 37, 9]]], [], [], [217, 104, 43, 7]]
['*', [['3', [], [], [], [375, 19, 37, 53]]], [], [], [313, 57, 57, 68]]
['(', [], [], [], [440, 22, 30, 100]]
['n', [], [], [], [466, 72, 43, 43]]
['*', [], [], [], [529, 38, 53, 84]]
['+', [], [], [], [640, 39, 45, 81]]
['e', [['*', [], [], [], [795, 12, 41, 52]]], [], [], [739, 43, 47, 77]]
['*', [['2', [], [], [], [974, 2, 29, 41]]], [], [], [892, 31, 64, 76]]
['+', [], [], [], [1041, 33, 42, 65]]
['*', [], [], [], [1123, 15, 69, 88]]
['+', [], [], [], [1235, 23, 41, 70]]
['1', [], [], [], [1317, 8, 17, 103]]
y 0.99996984
- 0.99999166
- 0.9999914
['y', [], [], [], [115, 2, 63, 111]]
['-', [], [], [['-', [], [], [], [249, 51, 36, 9]]], [248, 18, 42, 11]]
y=x^(3)(nx+e^(x)x

'x^2*e^(x) + 3*x^2*log(x) + x^2 + 2*x*e^(x) + 1'

In [3]:
import inferProgram
Four = inferProgram.FourOperation(5)

In [4]:
Four.infer_image('test_image/cs/A1.jpg')

1 0.99584913
2 0.99999714
8 0.99999845
- 0.99999857
2 0.99991333
0 0.9999995
* 0.9999995
( 0.9999943
6 0.66414183
0 0.9999902
5 0.8798781
- 0.99999976
PI 0.9998801
2 0.9999919
+ 0.99879885
5 0.594404
1 0.9934823
. 0.999995
n 0.9999682
- 0.9999999
PI 0.999998
4 0.9998419
) 0.9999627
2 True False
8 True False
2 True False
0 True False
* True False
( True False
6 True False
0 True False
5 True False
hello
- True True
PI True True
+ True False
1 True False
. True True
n True False
PI True True
4 True False
) True False
['1', [], [], [], [80, 116, 13, 109]]
['2', [], [], [], [112, 134, 53, 73]]
['8', [], [], [], [174, 102, 43, 102]]
['-', [], [], [], [240, 148, 42, 7]]
['2', [], [], [], [317, 107, 39, 78]]
['0', [], [], [], [366, 132, 34, 40]]
['*', [], [], [], [421, 121, 52, 62]]
['(', [], [], [], [491, 105, 40, 81]]
['6', [], [], [], [560, 124, 29, 53]]
['0', [], [], [], [600, 127, 36, 43]]
['5', [], [], [], [644, 128, 28, 42]]
['-', [['PI', [], [], [], [716, 57, 56, 60]]], [], [['2', [],

(True, '128-20*(cos((PI)/(2))+sin((PI)/(4)))')

In [1]:
import inferProgram
Ma = inferProgram.Martix(37)

In [5]:
result = Ma.infer_image('test_image/组委会手写数据集/新建文件夹/矩阵运算20.png')[1]
print(inferProgram.ToolBar.getMartrix().getResult(result))

( 0.9407512
- 1.0
7 0.83798337
1 0.9997999
4 0.99982697
6 0.9999925
) 0.9999969
+ 0.99999774
( 0.9126395
9 0.98992574
3 0.9539117
5 0.9984479
7 0.9995567
) 0.9999981
['[', [], [], [], [381, 175, 137, 671]]
[[['-1', '4'], ['7', '6']], [], [], [], [1619, 208, 152, 679]]
[']', [], [], [], [1619, 208, 152, 679]]
['+', [], [], [], [1993, 239, 208, 164]]
['[', [], [], [], [2437, 112, 117, 741]]
[[['3', '5'], ['9', '7']], [], [], [], [3600, 306, 178, 517]]
[']', [], [], [], [3600, 306, 178, 517]]
[[2 9][16 13]]


In [2]:
import inferProgram
result = inferProgram.Integral(151).infer_image('test_image/cs/4.jpg')[1]
print(result)
print(inferProgram.ToolBar.getIntegral().getResult(result))

# 0.9999993
( 0.9996123
* 0.99896324
2 0.999987
+ 0.9999994
e 0.99963975
* 0.99999475
+ 0.9999739
1 0.9968411
n 0.99998
* 0.99985886
) 0.99973506
d 0.99754274
* 0.99999785
['#', [], [], [], [131, 50, 121, 306]]
['(', [], [], [], [271, 161, 48, 116]]
['*', [['2', [], [], [], [430, 138, 42, 50]]], [], [], [347, 174, 64, 95]]
['+', [], [], [], [471, 174, 103, 82]]
['e', [['*', [], [], [], [688, 113, 46, 58]]], [], [], [599, 161, 98, 84]]
['+', [], [], [], [779, 152, 64, 87]]
['1', [], [], [], [892, 104, 18, 137]]
['n', [], [], [], [925, 164, 53, 69]]
['*', [], [], [], [1001, 127, 74, 111]]
[')', [], [], [], [1125, 89, 55, 157]]
['d', [], [], [], [1215, 53, 76, 171]]
['*', [], [], [], [1296, 123, 71, 85]]
#(x^(2)+e^(x)+1nx)dx
x^3/3 + x*log(x) - x + e^(x)


In [1]:
import inferProgram
aaa = inferProgram.Unk(66)
re = aaa.infer_image('test_image/cs/4.jpg')[1][0]
print(re)

( 0.5861249
( 0.9999434
* 0.99905914
2 0.9990101
+ 0.99996054
e 0.9982509
* 0.9999207
+ 0.9998871
1 0.98840326
n 0.9999925
* 0.9999361
) 0.9999863
n 0.69402367
* 0.9999559
['(', [], [], [], [131, 2, 121, 307]]
['(', [], [], [], [271, 114, 49, 117]]
['*', [['2', [], [], [], [430, 91, 42, 50]]], [], [], [346, 127, 65, 95]]
['+', [], [], [], [471, 127, 103, 83]]
['e', [['*', [], [], [], [687, 66, 47, 59]]], [], [], [599, 114, 98, 84]]
['+', [], [], [], [778, 105, 65, 87]]
['1', [], [], [], [892, 57, 18, 137]]
['n', [], [], [], [925, 117, 53, 69]]
['*', [], [], [], [1001, 80, 74, 111]]
[')', [], [], [], [1125, 42, 56, 158]]
['n', [], [], [], [1215, 6, 77, 171]]
['*', [], [], [], [1296, 76, 71, 86]]
((x^(2)+e^(x)+1nx)nx


In [8]:
np.array([[3,2, 1], [1, 2, 3], [3, 3, 2]])*np.array([[1, 2, 3], [2, 2, 4], [3, 2, 1]])-np.array([[1, 2, 1], [1, 1, 2],[1, 3, 1]])

array([[ 2,  2,  2],
       [ 1,  3, 10],
       [ 8,  3,  1]])

In [7]:
try:
    pass
except Exception:

array([2, 4])

In [4]:
import math

1.6094379124341003

In [4]:
import sympy